// data/cars.ts
import { RecodeCarCardProps } from "@/components/recodeComponentes/RecodeCarCard"

export const cars: RecodeCarCardProps[] = [
    {
        id: "car-1",
        nombre: "Toyota Corolla",
        marca: "Toyota",
        asientos: 5,
        puertas: 4,
        transmision: "Automática",
        combustible: "Gasolina",
        estado: "Disponible",
        nombreHost: "Carlos Mendoza",
        calificacion: 9.5,
        ubicacion: "La Paz, Bolivia",
        precioOficial: "$99",
        precioDescuento: "$120",
        precioPorDia: "$99",
    },
    {
        id: "car-2",
        nombre: "Nissan Versa",
        marca: "Nissan",
        asientos: 5,
        puertas: 4,
        transmision: "Manual",
        combustible: "Gas",
        estado: "Ocupado",
        nombreHost: "Luisa Ríos",
        calificacion: 9.2,
        ubicacion: "Santa Cruz, Bolivia",
        precioOficial: "$85",
        precioDescuento: "$100",
        precioPorDia: "$85",
    },
    {
        id: "car-3",
        nombre: "Hyundai Tucson",
        marca: "Hyundai",
        asientos: 5,
        puertas: 4,
        transmision: "Automática",
        combustible: "Diésel",
        estado: "Por liberarse",
        nombreHost: "Miguel Quispe",
        calificacion: 9.8,
        ubicacion: "Cochabamba, Bolivia",
        precioOficial: "$110",
        precioDescuento: "$135",
        precioPorDia: "$110",
    },
]
