// data/cars.ts
import { RecodeCarCardProps } from "@/components/recodeComponentes/RecodeCarCard"

export const cars: RecodeCarCardProps[] = [
    {
        id: "car-1",
        nombre: "Toyota Corolla",
        marca: "Toyota",
        asientos: 5,
        puertas: 4,
        transmision: "Automática",
        combustibles: ["Gasolina", "Gas"],
        estado: "Disponible",
        nombreHost: "Carlos Mendoza",
        calificacion: 9.5,
        ubicacion: "La Paz, Bolivia",
        precioOficial: "$99",
        precioDescuento: "$120",
        precioPorDia: "$99",
    },
    {
        id: "car-2",
        nombre: "Nissan Versa",
        marca: "Nissan",
        asientos: 5,
        puertas: 4,
        transmision: "Manual",
        combustibles: ["Gas"],
        estado: "Ocupado",
        nombreHost: "Luisa Ríos",
        calificacion: 9.2,
        ubicacion: "Santa Cruz, Bolivia",
        precioOficial: "$85",
        precioDescuento: "$100",
        precioPorDia: "$85",
    },
    {
        id: "car-3",
        nombre: "Hyundai Tucson",
        marca: "Hyundai",
        asientos: 5,
        puertas: 4,
        transmision: "Automática",
        combustibles: ["Diésel"],
        estado: "Por liberarse",
        nombreHost: "Miguel Quispe",
        calificacion: 9.8,
        ubicacion: "Cochabamba, Bolivia",
        precioOficial: "$110",
        precioDescuento: "$135",
        precioPorDia: "$110",
    },
    {
        id: "car-4",
        nombre: "Kia Sportage",
        marca: "Kia",
        asientos: 5,
        puertas: 4,
        transmision: "Automática",
        combustibles: ["Gasolina", "Eléctrico"],
        estado: "Disponible",
        nombreHost: "Andrea Salazar",
        calificacion: 8.9,
        ubicacion: "Sucre, Bolivia",
        precioOficial: "$105",
        precioDescuento: "$125",
        precioPorDia: "$105",
    },
    {
        id: "car-5",
        nombre: "Mazda 3",
        marca: "Mazda",
        asientos: 5,
        puertas: 4,
        transmision: "Manual",
        combustibles: ["Gasolina"],
        estado: "Disponible",
        nombreHost: "Esteban Núñez",
        calificacion: 9.0,
        ubicacion: "Tarija, Bolivia",
        precioOficial: "$95",
        precioDescuento: "$110",
        precioPorDia: "$95",
    },
    {
        id: "car-6",
        nombre: "Chevrolet Spark",
        marca: "Chevrolet",
        asientos: 4,
        puertas: 4,
        transmision: "Manual",
        combustibles: ["Gas", "Gasolina"],
        estado: "Ocupado",
        nombreHost: "Sofía Roca",
        calificacion: 8.7,
        ubicacion: "Oruro, Bolivia",
        precioOficial: "$70",
        precioDescuento: "$90",
        precioPorDia: "$70",
    },
    {
        id: "car-7",
        nombre: "Ford EcoSport",
        marca: "Ford",
        asientos: 5,
        puertas: 4,
        transmision: "Automática",
        combustibles: ["Gasolina"],
        estado: "Disponible",
        nombreHost: "Javier Pinto",
        calificacion: 9.4,
        ubicacion: "Trinidad, Bolivia",
        precioOficial: "$100",
        precioDescuento: "$120",
        precioPorDia: "$100",
    },
    {
        id: "car-8",
        nombre: "Renault Duster",
        marca: "Renault",
        asientos: 5,
        puertas: 4,
        transmision: "Manual",
        combustibles: ["Diésel", "Gas"],
        estado: "Por liberarse",
        nombreHost: "Luciana Romero",
        calificacion: 9.1,
        ubicacion: "Potosí, Bolivia",
        precioOficial: "$92",
        precioDescuento: "$110",
        precioPorDia: "$92",
    },
    {
        id: "car-9",
        nombre: "Volkswagen Golf",
        marca: "Volkswagen",
        asientos: 5,
        puertas: 4,
        transmision: "Automática",
        combustibles: ["Gasolina"],
        estado: "Disponible",
        nombreHost: "Carlos Ríos",
        calificacion: 9.3,
        ubicacion: "Santa Cruz, Bolivia",
        precioOficial: "$102",
        precioDescuento: "$118",
        precioPorDia: "$102",
    },
    {
        id: "car-10",
        nombre: "Tesla Model 3",
        marca: "Tesla",
        asientos: 5,
        puertas: 4,
        transmision: "Automática",
        combustibles: ["Eléctrico"],
        estado: "Disponible",
        nombreHost: "Natalia Cruz",
        calificacion: 9.9,
        ubicacion: "La Paz, Bolivia",
        precioOficial: "$130",
        precioDescuento: "$150",
        precioPorDia: "$130",
    },
    {
        id: "car-11",
        nombre: "Peugeot 208",
        marca: "Peugeot",
        asientos: 5,
        puertas: 4,
        transmision: "Manual",
        combustibles: ["Gasolina"],
        estado: "Ocupado",
        nombreHost: "Alejandro Vargas",
        calificacion: 8.8,
        ubicacion: "Cochabamba, Bolivia",
        precioOficial: "$88",
        precioDescuento: "$105",
        precioPorDia: "$88",
    },
    {
        id: "car-12",
        nombre: "Suzuki Swift",
        marca: "Suzuki",
        asientos: 4,
        puertas: 4,
        transmision: "Automática",
        combustibles: ["Gasolina"],
        estado: "Disponible",
        nombreHost: "Mariana Flores",
        calificacion: 9.0,
        ubicacion: "Sucre, Bolivia",
        precioOficial: "$90",
        precioDescuento: "$110",
        precioPorDia: "$90",
    },
    {
        id: "car-13",
        nombre: "Mitsubishi Outlander",
        marca: "Mitsubishi",
        asientos: 7,
        puertas: 5,
        transmision: "Automática",
        combustibles: ["Gasolina", "Eléctrico"],
        estado: "Por liberarse",
        nombreHost: "Iván Cordero",
        calificacion: 9.5,
        ubicacion: "La Paz, Bolivia",
        precioOficial: "$120",
        precioDescuento: "$145",
        precioPorDia: "$120",
    },
    {
        id: "car-14",
        nombre: "Jeep Renegade",
        marca: "Jeep",
        asientos: 5,
        puertas: 4,
        transmision: "Automática",
        combustibles: ["Gasolina", "Diésel"],
        estado: "Disponible",
        nombreHost: "Camila Ortega",
        calificacion: 9.2,
        ubicacion: "Santa Cruz, Bolivia",
        precioOficial: "$108",
        precioDescuento: "$130",
        precioPorDia: "$108",
    },
    {
        id: "car-15",
        nombre: "Audi A3",
        marca: "Audi",
        asientos: 5,
        puertas: 4,
        transmision: "Automática",
        combustibles: ["Gasolina"],
        estado: "Ocupado",
        nombreHost: "Fabián Ríos",
        calificacion: 9.6,
        ubicacion: "Tarija, Bolivia",
        precioOficial: "$125",
        precioDescuento: "$140",
        precioPorDia: "$125",
    },
    {
        id: "car-16",
        nombre: "BMW X1",
        marca: "BMW",
        asientos: 5,
        puertas: 4,
        transmision: "Automática",
        combustibles: ["Gasolina", "Diésel"],
        estado: "Disponible",
        nombreHost: "Melisa Guzmán",
        calificacion: 9.7,
        ubicacion: "Cochabamba, Bolivia",
        precioOficial: "$135",
        precioDescuento: "$155",
        precioPorDia: "$135",
    },
    {
        id: "car-17",
        nombre: "Mercedes-Benz Clase A",
        marca: "Mercedes-Benz",
        asientos: 5,
        puertas: 4,
        transmision: "Automática",
        combustibles: ["Gasolina"],
        estado: "Disponible",
        nombreHost: "David Pinto",
        calificacion: 9.8,
        ubicacion: "La Paz, Bolivia",
        precioOficial: "$145",
        precioDescuento: "$160",
        precioPorDia: "$145",
    },
    {
        id: "car-18",
        nombre: "Honda Civic",
        marca: "Honda",
        asientos: 5,
        puertas: 4,
        transmision: "Manual",
        combustibles: ["Gasolina", "Gas"],
        estado: "Por liberarse",
        nombreHost: "Roxana Morales",
        calificacion: 9.4,
        ubicacion: "Santa Cruz, Bolivia",
        precioOficial: "$98",
        precioDescuento: "$115",
        precioPorDia: "$98",
    }
]
